config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :cryptocurrencies

  post '/cryptocurrencies/:id/add_to_watchlist', to: 'cryptocurrencies_watchlist#add_to_watchlist', as: 'add_to_watchlist'
  delete '/cryptocurrencies/:id/remove_from_watchlist', to: 'cryptocurrencies_watchlist#remove_from_watchlist', as: 'remove_from_watchlist'
  
  resources :cryptocurrencies_watchlist, only: [:index, :show]
  
  resources :watchlists


  get 'cryptocurrencies/search', to: 'cryptocurrencies#search', as: 'search_cryptocurrencies'

  get 'home/about', to: 'home#about'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cryptocurrencies_watchlist.rb
class CryptocurrenciesWatchlist < ApplicationRecord
  belongs_to :cryptocurrency
  belongs_to :watchlist

  validates :cryptocurrency_id, presence: true
  validates :watchlist_id, presence: true
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
  paginates_per 50

  has_many :cryptocurrencies_watchlists
  has_many :watchlists, through: :cryptocurrencies_watchlists

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord

 has_many :watchlists
 has_many :cryptocurrencies, through: :watchlists


devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  has_many :cryptocurrencies_watchlists, dependent: :destroy
  has_many :cryptocurrencies, through: :cryptocurrencies_watchlists

  validates :user_id, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

end

app/controllers/cryptocurrencies_controller.rb
class CryptocurrenciesController < ApplicationController
  
  # GET /cryptocurrencies
  # Search for cryptocurrencies by symbol
  # Filter cryptocurrencies by category
  def index
    keyword = params[:keyword]
    category = params[:category]
  
    if keyword.present?
      case category
      when 'All'
        @cryptocurrencies = Cryptocurrency.where('symbol like ?', "%#{keyword}%").order('rank ASC').page(params[:page]).per(20)
      when 'Top 100'
        @cryptocurrencies = Cryptocurrency.where('symbol LIKE ?', "%#{keyword}%").where('rank <= 100').order('rank ASC').page(params[:page]).per(20)
      when 'Potential Tokens'
        @cryptocurrencies = Cryptocurrency.where('symbol LIKE ?', "%#{keyword}%").where('change > 0').order('rank ASC').page(params[:page]).per(20)
      else
        @cryptocurrencies = Cryptocurrency.order('rank ASC').page(params[:page]).per(50)
      end
    else
      @cryptocurrencies = Cryptocurrency.order('rank ASC').page(params[:page]).per(50)
    end
  
    @watchlist = current_user.watchlists.first if user_signed_in?
  end
  


  # GET /cryptocurrencies/:id
  def show
    
    if params[:keyword].present?
      redirect_to cryptocurrencies_path(keyword: params[:keyword])
    end

    @cryptocurrency = Cryptocurrency.find(params[:id])
    @sparkline_data = JSON.parse(@cryptocurrency.sparkline)  
  end


end

app/controllers/cryptocurrencies_watchlist_controller.rb
class CryptocurrenciesWatchlistController < ApplicationController
  before_action :authenticate_user!

  def index
      if params[:keyword].present?
        redirect_to cryptocurrencies_path(keyword: params[:keyword])
      end

    @watchlist = current_user.watchlists.find(params[:id]) if user_signed_in?
  end

  def add_to_watchlist
    @cryptocurrency = Cryptocurrency.find(params[:id])
    @user = current_user
    @watchlists = @user.watchlists
  
    # Find the selected watchlist by its ID
    selected_watchlist = @watchlists.find(params[:watchlist_id])
  
    if selected_watchlist.cryptocurrencies.include?(@cryptocurrency)
      flash[:alert] = "#{selected_watchlist.name} already includes #{@cryptocurrency}"
    else
      selected_watchlist.cryptocurrencies << @cryptocurrency
      flash[:notice] = "#{@cryptocurrency.symbol} has been added to #{selected_watchlist.name}"
    end
  
    redirect_to cryptocurrencies_path
  end
  

  def remove_from_watchlist
    @cryptocurrency = Cryptocurrency.find(params[:id])
    @watchlists = current_user.watchlists
  
    @watchlists.each do |watchlist|
      if watchlist.cryptocurrencies.include?(@cryptocurrency)
        watchlist.cryptocurrencies.delete(@cryptocurrency)
      end
    end
  
    flash[:notice] = "#{@cryptocurrency.symbol} has been removed from your watchlists."
    redirect_to cryptocurrencies_watchlist_path
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    if params[:keyword].present?
      redirect_to cryptocurrencies_path(keyword: params[:keyword])
    end
  end


  def about

      if params[:keyword].present?
        redirect_to cryptocurrencies_path(keyword: params[:keyword])
      end
    @about_me = <<-ABOUT_ME
    Hi there! I am Yifan, a full-stack development student at Red River College Polytechnic in Canada.
    Feel free to email(yifanlicode@gmail.com) me.
  ABOUT_ME
  end
  
end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController

  before_action :authenticate_user!, only: [:create, :destroy]

  # show all watchlists
  def index
      if params[:keyword].present?
        redirect_to cryptocurrencies_path(keyword: params[:keyword])
      end
    @watchlists = current_user.watchlists
    @new_watchlist = Watchlist.new
    @user = current_user
  end

  def new
    @watchlist = Watchlist.new
  end

  # show all the cryptocurrencies_watchlists for the user
  def show
    @watchlist = current_user.watchlists.find(params[:id])
    @user = current_user
  end

  # create a new watchlist
  def create
    @user = current_user
    @watchlist = @user.watchlists.build(watchlist_params)

    if @watchlist.save
      @watchlists = @user.watchlists # Set @watchlists variable after creating a new watchlist
      redirect_to watchlists_path, notice: 'Watchlist was successfully created.'
    else
      render :new
    end
  end

  def watchlist_params
    params.require(:watchlist).permit(:name)
  end

  # edit page for a watchlist name collection
  def edit
    @watchlist = current_user.watchlists.find(params[:id])
  end

  # update the name of a watchlist
  def update
    @watchlist = current_user.watchlists.find(params[:id])
    @watchlist.update(watchlist_params)
    redirect_to watchlists_path, notice: 'Watchlist was successfully updated.'
  end


  # delete a watchlist from watchlists

  def destroy
    @watchlist = current_user.watchlists.find(params[:id])
    @watchlist.cryptocurrencies.clear
    @watchlist.destroy
    redirect_to watchlists_path, notice: 'Watchlist was successfully destroyed.'
  end
 
 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cryptocurrencies/_cryptocurrency.html.erb
<div id="<%= dom_id(cryptocurrency) %>"
  style="box-shadow: 0 0 5px <%= cryptocurrency.color %>, 0 0 10px rgba(0, 0, 0, 0.1);"
  class="card">


  <div class="card-header bg-secondary text-white d-flex align-items-center">
    <%= image_tag(cryptocurrency.icon_url, class: "img-fluid img-coin",alt:"coins") %>
    <div class="ms-3">
      <h3 class="card-title my-auto">
        <%= cryptocurrency.name %>
      </h3>
    </div>
  </div>


  <div class="card-body">

    <p class="card-text">
      <strong>Rank:</strong> <%= cryptocurrency.rank %>
    </p>
    <p class="card-text">
      <strong>Price:</strong> $<%= number_with_precision(cryptocurrency.price, precision: 2) %>
    </p>
    <p class="card-text">
      <strong>Change:</strong>
      <span class="<%= cryptocurrency.change.to_f.negative? ? 'text-danger' : 'text-success' %>"><%= cryptocurrency.change %>%</span>
    </p>
    <p class="card-text">
      <strong>24h Volume:</strong> $<%= number_with_delimiter(cryptocurrency.volume_24h) %>
    </p>
    <p class="card-text">
      <strong>Market Cap:</strong> $<%= number_with_delimiter(cryptocurrency.market_cap) %>
    </p>
    <p class="card-text">
      <strong>Update:</strong> <%= cryptocurrency.updated_at %>
    </p>

    <div class="chart-container" style="width: 800px; height: 200px;" id="sparkline-data">
      <strong>Last 20 days:</strong>
      <canvas id="sparkline-<%= dom_id(cryptocurrency) %>"></canvas>
    </div>

    <br>
    <div class="mt-3">
      <strong>It belongs to these Watchlists:</strong>
      <ul>
        <% cryptocurrency.watchlists.each do |watchlist| %>
          <li><%= link_to watchlist.name, cryptocurrencies_watchlist_index_path(watchlist) %></li>
        <% end %>
      </ul>
    </div>

  </div>

</div>

app/views/cryptocurrencies/index.html.erb
<%# app/views/cryptocurrencies/index.html.erb %>



<%# ERD Conditional Part  %>
<% if user_signed_in? %>
  <div class="alert alert-success" role="alert">
    Welcome <%= current_user.email %>
  </div>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-primary" %>
<% end %>


<%= paginate @cryptocurrencies %>




<table class="table table-hover table-striped table-bordered">

   <thead class="table-dark custom-data-center">
        <tr>
          <th> Rank </th>
          <th> Logo </th>
          <th> Coin </th>
          <th> Price </th>
          <th> 1d </th>
          <th> 24h Volumn </th>
          <th> Market Cap </th>
          <th><%= link_to 'Watchlists', watchlists_path, class: 'watchlists-link' %></th>
        </tr>
    </thead>

  <tbody>
    <% @cryptocurrencies.each do |cryptocurrency| %>

      <tr>      

          <td class="custom-data-center"> <%= cryptocurrency.rank %> </td>
          <td class="custom-data-center"> 
            <%= image_tag cryptocurrency.icon_url,  class: "img-fluid img-coin custom-icon",alt:"icon" %>
          </td>
          <td class="custom-data-center"> 
            <%= link_to cryptocurrency.symbol,cryptocurrency_path(cryptocurrency) %> 
          </td>
          <td class="custom-data-right"> $<%= number_with_precision(cryptocurrency.price, precision: 2) %> </td>
          <td class="<%= cryptocurrency.change.to_f.negative? ? 'text-danger' : 'text-success' %> custom-data-center">
            <%= cryptocurrency.change %>%
          </td>
          <td class="custom-data-right"> $<%= number_with_delimiter(cryptocurrency.volume_24h) %> </td>
          <td class="custom-data-right"> $<%= number_with_delimiter(cryptocurrency.market_cap) %> </td>

          <%# CRUD  %>
         <td class="custom-data-center">
            <% if user_signed_in? %>
              <% if @watchlist&.cryptocurrencies&.include?(cryptocurrency) %>
                <%= form_with url: remove_from_watchlist_path(id: cryptocurrency.id), method: :delete do |form| %>
                  <%= form.submit 'Remove',class: 'btn btn-sm btn-danger' %>
                <% end %>
              <% else %>
                <%= form_with url: add_to_watchlist_path(id: cryptocurrency.id), method: :post do |form| %>
                  <%= form.submit 'Add', class: 'btn btn-sm btn-primary' %>
                  <%= form.select :watchlist_id, options_from_collection_for_select(current_user.watchlists, :id, :name), class: 'custom-select' %>
                <% end %>
              <% end %>
            <% else %>
              <%= button_to 'Add', add_to_watchlist_path(id: cryptocurrency.id), method: :post %>
            <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @cryptocurrencies %>

app/views/cryptocurrencies/show.html.erb
<%= render @cryptocurrency %>

 <div class="my-3">
  <div class="row justify-content-center">
  
    <div class="col-auto">
      <%= link_to "Back to Coins List",
          cryptocurrencies_path,
          class: "btn btn-secondary" %>
    </div>
    
    <div class="col-auto">
      <%= link_to "Add to watchlist",
          watchlists_path(@cryptocurrency),
          class: "btn btn-primary" %>
    </div>
    <div class="col-auto">
      <%= button_to "Delete from watchlist",
          watchlists_path(@watchlist),
          class: "btn btn-dark",
          method: :delete,
          data: { confirm: "Are you sure?" },
          autocomplete:"off" %>
    </div>
  </div>
</div>


  <%# Show sparkline with Chart.js %>
  <script type="text/javascript">
          
        document.addEventListener("DOMContentLoaded", function () {
          const ctx = document
            .getElementById("sparkline-<%= dom_id @cryptocurrency %>")
            .getContext("2d");

          const data = <%= @sparkline_data.to_json.html_safe %>;
          var chart = new Chart(ctx, {
            type: "line",
            data: {
              labels: Array.from({ length: data.length }, (_, i) => ""),
              datasets: [
                {
                  label: "Price",
                  data: data,
                  backgroundColor: "rgba(255, 99, 132, 0.2)",
                  borderColor: "rgba(255, 99, 132, 1)",
                  borderWidth: 1,
                  fill: true,
                  tension: 0.4,
                },
              ],
            },
            options: {
              responsive: true,
              maintainAspectRatio: false,
              scales: {
                x: {
                  display: false,
                },
                y: {
                  display: false,
                  ticks: {
                    callback: function (value, index, values) {
                      // Convert large numbers to abbreviated format
                      const abbreviations = ["K", "M", "B", "T"];
                      let newValue = value;
                      let suffix = "";
                      if (newValue >= 1000) {
                        const suffixIndex = Math.floor(Math.log10(newValue) / 3);
                        newValue /= 1000 ** suffixIndex;
                        suffix = abbreviations[suffixIndex - 1];
                      }
                      return newValue + suffix;
                    },
                  },
                  min: Math.min(...data) * 0.95,
                  max: Math.max(...data) * 1.05,
                },
              },
              plugins: {
                legend: {
                  display: false,
                },
                tooltip: {
                  enabled: false,
                },
              },
            },
          });
        });
  </script>


  

app/views/cryptocurrencies_watchlist/index.html.erb
<%# app/views/cryptocurrencies_watchlist/index.html.erb %>
<%# This is the default Watchlist for user  %>

<h3><%=@watchlist.name%></h3>

<table class="table table-hover table-striped table-bordered">

<thead class="table-dark custom-data-center">
    <tr>
      <th> Rank </th>
      <th> Logo </th>
      <th> Coin </th>
      <th> Price </th>
      <th> 1d </th>
      <th> 24h Volumn </th>
      <th> Market Cap </th>
      <th> Watchlist </th>
    </tr>
</thead>

  <tbody>
 <% @watchlist.cryptocurrencies.each do |cw| %>
      <% cryptocurrency = cw %>  
      <tr>
         <td class="custom-data-center"> <%= cryptocurrency.rank %> </td>
          <td class="custom-data-center"> 
            <%= image_tag cryptocurrency.icon_url,  class: "img-fluid img-coin custom-icon",alt:"icon" %>
          </td>
          <td class="custom-data-center"> 
            <%= link_to cryptocurrency.symbol,cryptocurrency_path(cryptocurrency) %> 
          </td>
          <td class="custom-data-right"> $<%= number_with_precision(cryptocurrency.price, precision: 2) %> </td>
          <td class="<%= cryptocurrency.change.to_f.negative? ? 'text-danger' : 'text-success' %> custom-data-center">
            <%= cryptocurrency.change %>%
          </td>
          <td class="custom-data-right"> $<%= number_with_delimiter(cryptocurrency.volume_24h) %> </td>
          <td class="custom-data-right"> $<%= number_with_delimiter(cryptocurrency.market_cap) %> </td>
           <td class="custom-data-center"> 
           
            <%= button_to 'Delete', remove_from_watchlist_path(id: cryptocurrency.id), method: :delete ,autocomplete: :off %>
           
           </td>

      </tr>
    <% end %>
  </tbody>
</table>


<%# show the user's all the watchlist %>

<div>
<%= link_to 'View All Watchlists', watchlists_path, class: 'btn btn-primary' %>
</div>

app/views/home/_footer.html.erb
<footer class="footer bg-light py-5 text-center">
  <div class="container">
    <div class="row justify-content-between align-items-center">
      <div class="col-lg-4 text-center text-lg-start">
        <p class="mb-0">&copy; 2023 CoinRocket APP</p>
      </div>

      <div class="col-lg-4 text-center">
        <ul class="list-inline mb-0">
          <li class="list-inline-item me-4">
            <a href="https://twitter.com/yifantech" target="_blank" class="text-dark">
              <i class="fab fa-twitter fa-2x"></i>
            </a>
          </li>
          <li class="list-inline-item me-4">
            <a href="https://github.com/yifanlicode" target="_blank" class="text-dark">
              <i class="fab fa-github fa-2x"></i>
            </a>
          </li>
          <li class="list-inline-item me-4">
            <a href="https://www.linkedin.com/in/yifanlicode/" target="_blank" class="text-dark">
              <i class="fab fa-linkedin fa-2x"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>
<!-- End of Footer -->

app/views/home/_header.html.erb
<nav class="navbar bg-primary navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <div class="navbar-brand d-flex align-items-center">
      <%= link_to cryptocurrencies_path do %>
        <img src="<%= asset_path('doge.png') %>" alt="logo" class="img-logo">
      <% end %>
      <%= link_to 'CoinRocket', cryptocurrencies_path, class: "navbar-brand"%>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <%# Home Page %>
        <li class="nav-item ms-lg-2 ">
          <%= link_to "Home", root_path, class: "nav-link #{'active' if controller_name == 'home' && action_name == 'index'}" %>
        </li>

        <%# About APIs %>
        <li class="nav-item ms-lg-2 ">
          <%= link_to "About", home_about_path, class: "nav-link #{'active' if controller_name == 'home' && action_name == 'about'}" %>
        </li>

        <%# Token List Page %>
        <li class="nav-item ms-lg-2 ">
          <%= link_to "Coins", cryptocurrencies_path, class: "nav-link #{'active' if controller_name == 'cryptocurrencies' && action_name == 'index'}" %>
        </li>

        <%# Search %>
        <li class="nav-item ms-lg-3">
          <%= form_tag(cryptocurrencies_path, method: :get, class: "d-flex", role: "search") do %>
            <%= text_field_tag :keyword, params[:keyword], placeholder: 'Enter Token Name' %>
            <%= select_tag :category, options_for_select(['All', 'Top 100', 'Potential Tokens'], params[:category]) %>
            <button class="btn btn-outline-success" type="submit">Search</button>
          <% end %>
        </li>

        <% if user_signed_in? %>
          <%# Watchlists %>
          <li class="nav-item ms-lg-2 ">
            <%= link_to "Watchlists", watchlists_path, class: "nav-link #{'active' if controller_name == 'watchlists' && action_name == 'index'}" %>
          </li>

          <%# Profile %>
          <li class="nav-item ms-lg-2 ">
            <%= link_to "Profile", edit_user_registration_path, class: "nav-link #{'active' if controller_name == 'registrations' && action_name == 'edit'}" %>
          </li>

          <%# Log Out %>
          <li class="nav-item ms-lg-2 ">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link #{'active' if controller_name == 'sessions' && action_name == 'destroy'}" %>
          </li>

        <% else %>
          <%# Sign Up %>
          <li class="nav-item ms-lg-2 ">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link #{'active' if controller_name == 'registrations' && action_name == 'new'}" %>
          </li>

          <%# Log In %>
          <li class="nav-item ms-lg-2 ">
            <%= link_to "Log In", new_user_session_path, class: "nav-link #{'active' if controller_name == 'sessions' && action_name == 'new'}" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<br>

app/views/home/about.html.erb
<!-- app/views/home/about.html.erb -->

<div class="content container min-vh-100">

  <div class="about-content">   
    <h3>CoinRocket App</h3>
    <p>CoinRocket is a Ruby on Rails web application that is perfect for anyone looking to get a 360 overview of the crypto markets.</p>
  </div>

  <div class="about-content">  
    <h3>Features</h3>
    <ul>
      <li>Live prices - Stay up-to-date with the latest prices of over 200 cryptocurrencies</li>
      <li>Advanced Search and Filtering - Easily find and filter cryptocurrencies</li>
      <li>Detailed Cryptocurrency Information - Dive into the details of each cryptocurrency</li>
      <li>Personal Watchlist - Create your own watchlist and keep track of your favorite cryptocurrencies.</li>
      <li>Effortless Management - Seamlessly manage your watchlist by CRUD</li>
    </ul>
  </div>

  <div class="about-content">
    <h3>Data Sources & APIs</h3>
    <ul>
      <li><a href="https://api.coinranking.com/v2/coins" target="_blank">CoinRanking API</a> - Access real-time and reliable cryptocurrency data from CoinRanking's API.</li>
      <li><a href="https://github.com/faker-ruby/faker" target="_blank">Faker Gem</a> - Utilize the Faker gem to generate realistic fake user data for testing and demonstration purposes.</li>
    </ul>
  </div>

  <div class="about-content">
    <h3>Database ERD</h3>
    <img src="https://s2.loli.net/2023/07/07/DCW964w2BqjHRgV.png" class="img-fluid img-erd" alt="Database ERD">
  </div>

  <div class="about-content">
    <h3>Learn from the project</h3>
    <ol>
      <li>MVC Organization</li>
      <li>Using data from public and private APIs</li>
      <li>CRUD Scaffold</li>
      <li>Ruby on Rails Gems</li>
      <li>Database Association</li>
      <li>Fun with Controllers</li>
      <li>Git, Github</li>
    </ol>
  </div>

  <div class="about-content">
    <h3>About Me</h3>
    <p><%= @about_me %></p>

  </div>

</div>

app/views/home/index.html.erb
<div class="container" style="height: 75vh;">
  <div class="row d-flex flex-grow-1">
    <div class="col-lg-4 mt-5 d-flex">
      <div class="content text-center flex-grow-1">
        <h2 class="text-center mb-4">Shit Coin?  <br> Yes.. </h2>
        <img src="<%= asset_path('dogedoge.jpg') %>" alt="Image" class="img-fluid">
        <br>
        <p class="text-center">Welcome aboard the CoinRocket</p>
      </div>
    </div>
    <div class="col-lg-4 mt-5 d-flex">
      <div class="content flex-grow-1">
        <h2 class="text-center mb-4">Buckle up<br> Risk-Takers!</h2>
        <p class="text-center">We promise a rollercoaster ride through the crypto chaos</p>
        <p class="text-center">Experience heart-stopping live price swings and explore the wildest coins</p>
        <p class="text-center"> Create your own watchlist and enjoy the journey of losing money.</p>
        <p class="text-center">It's the perfect place to discover more ways to lose sleep 😄</p>
      </div>
    </div>
    <div class="col-lg-4 mt-5 d-flex">
      <div class="content flex-grow-1">
        <h2 class="text-center mb-4">Attention<br> What's Inside?</h2>
        <p class="text-center">Stay on the crypto rollercoaster with real-time prices of over 200 cryptocurrencies</p>
        <p class="text-center">Dive into the details of each cryptocurrency to explore more invaluable Tokens</p>
        <p class="text-center">Manage your watchlist carefully and never miss a chance to watch a shit coin 🚀</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/watchlists/edit.html.erb
<div class="container" style="height:600px">
  <div class="row justify-content-center">
  <div class="col-md-6">
 <br>
      <h3 class="fw-normal mb-4">Edit Watchlist</h3>

      <%= form_for(@watchlist, url: watchlist_path(@watchlist), method: :patch) do |f| %>
        <div class="mb-3">
          <div>
            Watchlist <%= f.label :name %> :
            <%= f.text_field :name, class: "form-control placeholder-gray" %>
          </div>
        </div>
 <br>

        <div class="actions justify-content-center">
         <%= link_to "Back", watchlists_path, class: "btn btn-secondary" %>
          <%= f.submit "Update",class: "btn btn-success" %>
          <%= button_to "Delete", watchlist_path(@watchlist), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/watchlists/index.html.erb
<div class="container" style="height:550px">
  <div class="row">
    <div class="col-12">
      <h3>Watchlists</h3>
      <p >Welcome,<%= @user.email %>, <%= link_to "Create your new watchlist", new_watchlist_path %> here !</p>
    </div>
  </div>
  <br>

 <table class="table table-hover table-striped table-bordered">
    <thead class="table-dark custom-data-center">
      <tr>
        <th> Watchlist </th>
        <th> </th>
      </tr>
    </thead>

    <tbody>
      <% @watchlists.each do |watchlist| %>
        <tr> 
        <td class="custom-data-center"> 
          <%= link_to watchlist.name, cryptocurrencies_watchlist_index_path(id: watchlist.id) %>
        </td>

      <td class="custom-data-center"> 
        <div class="button-group ">
          <%= button_to "Edit", edit_watchlist_path(watchlist), method: :get %>
          <%= button_to "Delete", watchlist_path(watchlist), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </td>

      
      <% end %>

    </tbody>      

  </table>
  

app/views/watchlists/show.html.erb
<p>Hello </p>